import type { MarketplaceProduct } from '@/types';

export const MARKETPLACE_CATALOG: MarketplaceProduct[] = [
  {
    id: 'mp_food_1',
    name: 'Alimento Premium Adulto',
    slug: 'alimento-premium-adulto',
    category: 'food',
    price: 89000,
    rating: 4.8,
    reviewCount: 214,
    shortDescription: 'Proteína real, sin colorantes artificiales',
    description:
      'Alimento balanceado para perros adultos con pollo como primer ingrediente. Fórmula digestiva con prebióticos, omega 3 y vitaminas esenciales para energía diaria y pelaje saludable.',
    imageEmoji: '🥩',
    gallery: ['🥩', '🐕', '✨'],
    inStock: true,
    tags: ['perros', 'adulto', 'premium'],
  },
  {
    id: 'mp_food_2',
    name: 'Snacks Naturales Mix',
    slug: 'snacks-naturales-mix',
    category: 'food',
    price: 32000,
    rating: 4.6,
    reviewCount: 98,
    shortDescription: 'Premios crujientes 100% naturales',
    description:
      'Mix de snacks horneados con camote, pollo deshidratado y arándanos. Ideal para entrenamiento y recompensas. Sin granos ni azúcares añadidos.',
    imageEmoji: '🦴',
    gallery: ['🦴', '🍠', '🐾'],
    inStock: true,
    tags: ['snacks', 'natural'],
  },
  {
    id: 'mp_groom_1',
    name: 'Kit Aseo Spa Pawalk',
    slug: 'kit-aseo-spa',
    category: 'grooming',
    price: 65000,
    rating: 4.7,
    reviewCount: 156,
    shortDescription: 'Shampoo, acondicionador y cepillo suave',
    description:
      'Kit completo de grooming con shampoo hipoalergénico, acondicionador hidratante y cepillo anti-nudos. Aroma suave, pH balanceado para piel sensible.',
    imageEmoji: '🛁',
    gallery: ['🛁', '✂️', '🧴'],
    inStock: true,
    tags: ['aseo', 'kit'],
  },
  {
    id: 'mp_groom_2',
    name: 'Cepillo Deslanador Pro',
    slug: 'cepillo-deslanador',
    category: 'grooming',
    price: 45000,
    rating: 4.5,
    reviewCount: 73,
    shortDescription: 'Reduce muda hasta un 90%',
    description:
      'Cepillo ergonómico de acero inoxidable para pelo largo y corto. Botón expulsor de pelo, mango antideslizante y diseño apto para uso frecuente.',
    imageEmoji: '✂️',
    gallery: ['✂️', '🐩', '💫'],
    inStock: true,
    tags: ['cepillo', 'muda'],
  },
  {
    id: 'mp_toy_1',
    name: 'Pelota Interactiva LED',
    slug: 'pelota-interactiva-led',
    category: 'toys',
    price: 38000,
    rating: 4.4,
    reviewCount: 121,
    shortDescription: 'Estimula juego activo en interiores',
    description:
      'Pelota resistente con luces LED activadas por movimiento. Material no tóxico, rebote impredecible y tamaño ideal para perros medianos.',
    imageEmoji: '🎾',
    gallery: ['🎾', '💡', '🐕'],
    inStock: true,
    tags: ['juguetes', 'interactivo'],
  },
  {
    id: 'mp_toy_2',
    name: 'Hueso Mordedor Reforzado',
    slug: 'hueso-mordedor',
    category: 'toys',
    price: 28000,
    rating: 4.3,
    reviewCount: 64,
    shortDescription: 'Duradero y seguro para mordida fuerte',
    description:
      'Hueso de nylon reforzado con textura dental. Ayuda a reducir ansiedad y mantiene dientes limpios. Disponible en tamaño M.',
    imageEmoji: '🦴',
    gallery: ['🦴', '😁', '🐶'],
    inStock: false,
    tags: ['mordedor'],
  },
  {
    id: 'mp_vet_1',
    name: 'Suplemento Articular Plus',
    slug: 'suplemento-articular',
    category: 'veterinary',
    price: 72000,
    rating: 4.9,
    reviewCount: 189,
    shortDescription: 'Glucosamina y condroitina para movilidad',
    description:
      'Suplemento veterinario recomendado para perros senior o activos. Apoya articulaciones, cartílago y movilidad. Presentación 60 tabletas masticables.',
    imageEmoji: '💊',
    gallery: ['💊', '🦴', '❤️'],
    inStock: true,
    tags: ['salud', 'articulaciones'],
  },
  {
    id: 'mp_vet_2',
    name: 'Kit Primeros Auxilios Pet',
    slug: 'kit-primeros-auxilios',
    category: 'veterinary',
    price: 95000,
    rating: 4.6,
    reviewCount: 52,
    shortDescription: 'Esencial para emergencias en casa o paseo',
    description:
      'Incluye gasas estériles, vendas, antiséptico pet-safe, pinzas, termómetro y guía de emergencias. Estuche compacto resistente al agua.',
    imageEmoji: '🏥',
    gallery: ['🏥', '🩹', '📋'],
    inStock: true,
    tags: ['emergencia', 'kit'],
  },
  {
    id: 'mp_svc_1',
    name: 'Baño & Corte a Domicilio',
    slug: 'bano-corte-domicilio',
    category: 'services',
    price: 85000,
    rating: 4.8,
    reviewCount: 302,
    shortDescription: 'Groomer certificado en tu puerta',
    description:
      'Servicio profesional de baño, secado, corte de uñas y limpieza de oídos. Incluye reporte post-servicio y recomendaciones personalizadas.',
    imageEmoji: '✨',
    gallery: ['✨', '🚐', '🐩'],
    inStock: true,
    tags: ['servicio', 'domicilio'],
  },
  {
    id: 'mp_svc_2',
    name: 'Consulta Veterinaria Virtual',
    slug: 'consulta-vet-virtual',
    category: 'services',
    price: 55000,
    rating: 4.7,
    reviewCount: 178,
    shortDescription: 'Veterinario en línea en menos de 30 min',
    description:
      'Videoconsulta con veterinario colegiado. Ideal para seguimiento, dudas de alimentación o evaluación inicial. Incluye resumen por chat.',
    imageEmoji: '👨‍⚕️',
    gallery: ['👨‍⚕️', '📱', '🐾'],
    inStock: true,
    tags: ['telemedicina'],
  },
  {
    id: 'mp_food_3',
    name: 'Comida Húmeda Gatos',
    slug: 'comida-humeda-gatos',
    category: 'food',
    price: 24000,
    rating: 4.5,
    reviewCount: 87,
    shortDescription: 'Salmón en salsa, lata 85g x12',
    description:
      'Pack de 12 latas con salmón atlántico, taurina y minerales esenciales. Textura suave para gatos exigentes.',
    imageEmoji: '🐟',
    gallery: ['🐟', '🐱', '🍽️'],
    inStock: true,
    tags: ['gatos', 'húmedo'],
  },
  {
    id: 'mp_toy_3',
    name: 'Rascador Torre Deluxe',
    slug: 'rascador-torre',
    category: 'toys',
    price: 120000,
    rating: 4.6,
    reviewCount: 41,
    shortDescription: 'Torre sisal con plataformas y juguetes',
    description:
      'Rascador vertical de 90cm con sisal natural, plataformas acolchadas y colgantes interactivos. Base antivuelco.',
    imageEmoji: '🐱',
    gallery: ['🐱', '🌿', '🏰'],
    inStock: true,
    tags: ['gatos', 'rascador'],
  },
];
