import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Onboarding
    'welcome.title': 'Bienvenido a Pawalk',
    'welcome.subtitle': 'Conexión y cuidado animal',
    'welcome.slide1.title': 'Encuentra paseadores verificados',
    'welcome.slide1.desc': 'Todos nuestros paseadores están verificados y certificados',
    'welcome.slide2.title': 'Seguimiento en tiempo real',
    'welcome.slide2.desc': 'Rastrea el paseo de tu mascota en vivo',
    'welcome.slide3.title': 'Seguro y confiable',
    'welcome.slide3.desc': 'Pagos seguros y garantía de satisfacción',
    'get.started': 'Comenzar',
    'login': 'Iniciar sesión',
    'signup': 'Registrarse',
    'signup.email.exists.title': 'Este correo ya está registrado',
    'signup.email.exists.message':
      'Ya tienes una cuenta con este correo. Puedes iniciar sesión o registrarte con un email diferente.',
    'signup.email.exists.login': 'Iniciar sesión',
    'signup.email.exists.change': 'Usar otro correo',
    'language': 'Idioma',
    'theme': 'Tema',
    'light': 'Claro',
    'dark': 'Oscuro',
    'forgot.password': '¿Olvidaste tu contraseña?',
    'no.account': '¿No tienes cuenta?',
    'have.account': '¿Ya tienes cuenta?',
    'or': 'o',
    'continue.with': 'Continuar con',
    'accept.terms': 'Acepto los términos y condiciones',

    // Navigation
    'nav.home': 'Inicio',
    'nav.bookings': 'Reservas',
    'nav.pets': 'Mascotas',
    'nav.profile': 'Perfil',

    // Reservations
    'reservations.title': 'Mis Reservas',
    'reservations.subtitle': 'Administra tus paseos programados',
    'reservations.loading': 'Cargando reservas...',
    'reservations.refresh': 'Actualizar',
    'reservations.retry': 'Reintentar',
    'reservations.track': 'Ver seguimiento en vivo',
    'reservations.startsIn': 'Comienza en {minutes} min',
    'reservations.count': '{count} reservas en total',
    'reservations.tab.upcoming': 'Próximas',
    'reservations.tab.active': 'En curso',
    'reservations.tab.history': 'Historial',
    'reservations.status.scheduled': 'Programada',
    'reservations.status.active': 'En curso',
    'reservations.status.completed': 'Completada',
    'reservations.status.cancelled': 'Cancelada',
    'reservations.error.title': 'No pudimos cargar tus reservas',
    'reservations.empty.upcoming.title': 'Sin reservas próximas',
    'reservations.empty.upcoming.desc': 'Cuando reserves un paseo, aparecerá aquí automáticamente.',
    'reservations.empty.active.title': 'No hay paseos en curso',
    'reservations.empty.active.desc': 'Los paseos activos aparecerán aquí con acceso al seguimiento en vivo.',
    'reservations.empty.history.title': 'Sin historial aún',
    'reservations.empty.history.desc': 'Tus paseos completados se mostrarán en esta sección.',

    // Profile
    'profile.title': 'Mi Perfil',
    'profile.subtitle.view': 'Tu cuenta y preferencias',
    'profile.subtitle.edit': 'Actualiza tu información',
    'profile.loading': 'Cargando perfil...',
    'profile.edit': 'Editar perfil',
    'profile.edit.photo': 'Toca el ícono para cambiar foto',
    'profile.notSet': 'Sin configurar',
    'profile.save.success': 'Cambios guardados correctamente',
    'profile.save.error': 'No se pudo guardar el perfil',
    'profile.logout': 'Cerrar sesión',
    'profile.section.contact': 'Información de contacto',
    'profile.section.pets': 'Mis mascotas',
    'profile.section.pets.desc': 'Resumen de tus compañeros registrados',
    'profile.section.account': 'Cuenta',
    'profile.section.preferences': 'Privacidad y preferencias',
    'profile.section.accessibility': 'Accesibilidad',
    'profile.field.name': 'Nombre completo',
    'profile.field.email': 'Correo electrónico',
    'profile.field.phone': 'Teléfono',
    'profile.field.neighborhood': 'Barrio',
    'profile.field.emergency': 'Contacto de emergencia',
    'profile.field.emergencyPhone': 'Teléfono de emergencia',
    'profile.pets.viewAll': 'Ver todas',
    'profile.pets.empty': 'Aún no has registrado mascotas',
    'profile.pets.more': '+{count} más',
    'profile.account.security': 'Seguridad',
    'profile.account.security.desc': 'Contraseña protegida con Supabase Auth',
    'profile.account.member': 'Membresía',
    'profile.account.member.desc': 'Plan Pawalk gratuito',
    'profile.prefs.notifications': 'Notificaciones activas',
    'profile.prefs.push': 'Push',
    'profile.prefs.email': 'Email',
    'profile.prefs.sms': 'SMS',
    'profile.prefs.none': 'Ninguna activa',
    'profile.prefs.push.desc': 'Alertas en tiempo real',
    'profile.prefs.email.desc': 'Confirmaciones y resúmenes',
    'profile.prefs.sms.desc': 'Solo urgencias',
    'profile.a11y.largeText': 'Texto grande',
    'profile.a11y.largeText.desc': 'Aumenta el tamaño del texto en la app',
    'profile.a11y.reduceMotion': 'Reducir animaciones',
    'profile.a11y.reduceMotion.desc': 'Minimiza movimiento en transiciones',

    // Home
    'home.title': '¿Dónde necesitas un paseador?',
    'home.search': 'Buscar por ubicación...',
    'home.nearby': 'Paseadores cercanos',
    'home.filters': 'Filtros',
    'home.distance': 'Distancia',
    'home.price': 'Precio',
    'home.rating': 'Calificación',
    'home.service': 'Servicio',

    // Walker Profile
    'walker.verified': 'Verificado',
    'walker.experience': 'Experiencia',
    'walker.years': 'años',
    'walker.reviewsTitle': 'Reseñas',
    'walker.reviews.viewAll': 'Ver todas las reseñas',
    'walker.reviews': 'reseñas',
    'walker.book': 'Reservar paseo',
    'walker.about': 'Acerca de',
    'walker.certifications': 'Certificaciones',
    'walker.cert.id': 'Verificación de identidad',
    'walker.cert.background': 'Antecedentes judiciales',
    'walker.cert.firstaid': 'Primeros auxilios veterinarios',

    // Pet Profile
    'pet.add': 'Agregar mascota',
    'pet.name': 'Nombre',
    'pet.breed': 'Raza',
    'pet.age': 'Edad',
    'pet.weight': 'Peso',
    'pet.behavior': 'Comportamiento',
    'pet.vaccinations': 'Vacunas',
    'pet.friendly': 'Amigable',
    'pet.energetic': 'Enérgico',
    'pet.shy': 'Tímido',
    'pet.trained': 'Entrenado',
    'pet.playful': 'Juguetón',
    'pet.calm': 'Tranquilo',
    'pet.gender': 'Sexo',
    'pet.male': 'Macho',
    'pet.female': 'Hembra',
    'pet.species': 'Tipo',
    'pet.dog': 'Perro',
    'pet.cat': 'Gato',

    // Booking
    'booking.select.date': 'Seleccionar fecha',
    'booking.select.time': 'Seleccionar hora',
    'booking.duration': 'Duración',
    'booking.30min': '30 minutos',
    'booking.60min': '60 minutos',
    'booking.90min': '90 minutos',
    'booking.terms': 'Términos y condiciones',
    'booking.accept': 'Acepto los términos y reglas de convivencia',
    'booking.accept.confirmed': 'Términos aceptados',
    'booking.cancel.policy': 'Política de cancelación',
    'booking.rules': 'Reglas de convivencia',
    'booking.confirmed.title': '¡Reserva confirmada!',
    'booking.confirmed.subtitle': 'Tu paseo ha sido agendado exitosamente',
    'booking.confirmed.walker': 'Paseador profesional verificado',
    'booking.confirmed.date': 'Fecha del paseo',
    'booking.confirmed.time': 'Hora y duración',
    'booking.confirmed.note': 'Estado de la reserva',
    'booking.confirmed.upcoming': 'Aparecerá en Próximas reservas. El seguimiento en vivo se habilitará cuando comience el paseo.',
    'booking.confirmed.viewReservations': 'Ver mis reservas',
    'booking.confirmed.backHome': 'Volver al inicio',
    'booking.confirmed.hint': 'Recibirás recordatorios antes de tu paseo',

    // Checkout
    'checkout.summary': 'Resumen',
    'checkout.service': 'Servicio de paseo',
    'checkout.platform.fee': 'Tarifa de plataforma (15%)',
    'checkout.total': 'Total',
    'checkout.payment': 'Método de pago',
    'checkout.confirm': 'Confirmar pago',

    // Live Tracking
    'tracking.walker.on.way': 'Paseador en camino',
    'tracking.walk.started': 'Paseo iniciado',
    'tracking.eta': 'Tiempo estimado',
    'tracking.emergency': 'Emergencia',
    'tracking.contact.walker': 'Contactar paseador',
    'tracking.completed': '¡Paseo completado! 🎉',

    // Notifications
    'notif.booking.confirmed': 'Reserva confirmada',
    'notif.walk.started': 'Paseo iniciado',
    'notif.walk.completed': 'Paseo completado',
    'notif.payment.confirmed': 'Pago confirmado',
    'notif.vaccination.reminder': 'Recordatorio de vacunación',

    // Reminders
    'reminders.title': 'Recordatorios',
    'reminders.subtitle': 'No olvides el cuidado de tus mascotas',
    'reminders.badge': 'Cuidado programado',
    'reminders.add': 'Nuevo recordatorio',
    'reminders.edit': 'Editar recordatorio',
    'reminders.create': 'Crear recordatorio',
    'reminders.manage': 'Administrar recordatorios',
    'reminders.sectionDesc': 'Vacunas, medicación, paseos y más',
    'reminders.sectionEmpty': 'Programa recordatorios para el cuidado diario',
    'reminders.sectionPending': '{count} pendientes',
    'reminders.sectionOverdue': '{count} vencidos',
    'reminders.markComplete': 'Marcar como completado',
    'reminders.snooze': 'Recordar en 10 min',
    'reminders.dismiss': 'Cerrar',
    'reminders.overdueHint': 'Este recordatorio ya venció',
    'reminders.noPetSelected': 'Sin mascota asignada',
    'reminders.tab.upcoming': 'Próximos',
    'reminders.tab.overdue': 'Vencidos',
    'reminders.tab.completed': 'Completados',
    'reminders.tab.all': 'Todos',
    'reminders.status.upcoming': 'Próximo',
    'reminders.status.overdue': 'Vencido',
    'reminders.status.completed': 'Completado',
    'reminders.empty.title': 'Sin recordatorios',
    'reminders.empty.desc': 'Crea tu primer recordatorio para vacunas, medicación, paseos y más.',
    'reminders.delete.title': 'Eliminar recordatorio',
    'reminders.delete.desc': '¿Eliminar "{title}"? Esta acción no se puede deshacer.',
    'reminders.alert.title': 'Recordatorio',
    'reminders.form.subtitle': 'Programa alertas para el cuidado de tu mascota',
    'reminders.form.title': 'Título',
    'reminders.form.titlePlaceholder': 'Ej. Vacuna anual, pastilla antipulgas',
    'reminders.form.pet': 'Mascota',
    'reminders.form.noPet': 'Sin mascota específica',
    'reminders.form.category': 'Categoría',
    'reminders.form.date': 'Fecha',
    'reminders.form.time': 'Hora',
    'reminders.form.notes': 'Notas (opcional)',
    'reminders.form.notesPlaceholder': 'Detalles, dosis, veterinaria...',
    'reminders.form.alertHint': 'Te avisaremos en la fecha y hora programadas',
    'reminders.category.vaccination': 'Vacunas',
    'reminders.category.medication': 'Medicación',
    'reminders.category.deworming': 'Desparasitación',
    'reminders.category.walks': 'Paseos',
    'reminders.category.feeding': 'Alimentación',
    'reminders.category.grooming': 'Aseo',
    'reminders.category.vet_visit': 'Cita veterinaria',

    // Common
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'edit': 'Editar',
    'delete': 'Eliminar',
    'confirm': 'Confirmar',
    'back': 'Volver',
    'next': 'Siguiente',
    'skip': 'Omitir',
    'done': 'Listo',
    'from': 'desde',
    'min': 'min',
    'hour': 'hora',
    'available': 'Disponible',
  },
  en: {
    // Onboarding
    'welcome.title': 'Welcome to Pawalk',
    'welcome.subtitle': 'Connection and animal care',
    'welcome.slide1.title': 'Find verified walkers',
    'welcome.slide1.desc': 'All our walkers are verified and certified',
    'welcome.slide2.title': 'Real-time tracking',
    'welcome.slide2.desc': "Track your pet's walk live",
    'welcome.slide3.title': 'Safe and reliable',
    'welcome.slide3.desc': 'Secure payments and satisfaction guarantee',
    'get.started': 'Get Started',
    'login': 'Log In',
    'signup': 'Sign Up',
    'signup.email.exists.title': 'This email is already registered',
    'signup.email.exists.message':
      'An account already exists with this email. Log in or sign up with a different address.',
    'signup.email.exists.login': 'Log in',
    'signup.email.exists.change': 'Use a different email',
    'language': 'Language',
    'theme': 'Theme',
    'light': 'Light',
    'dark': 'Dark',
    'forgot.password': 'Forgot your password?',
    'no.account': "Don't have an account?",
    'have.account': 'Already have an account?',
    'or': 'or',
    'continue.with': 'Continue with',
    'accept.terms': 'I accept the terms and conditions',

    // Navigation
    'nav.home': 'Home',
    'nav.bookings': 'Bookings',
    'nav.pets': 'Pets',
    'nav.profile': 'Profile',

    // Reservations
    'reservations.title': 'My Reservations',
    'reservations.subtitle': 'Manage your scheduled walks',
    'reservations.loading': 'Loading reservations...',
    'reservations.refresh': 'Refresh',
    'reservations.retry': 'Try again',
    'reservations.track': 'View live tracking',
    'reservations.startsIn': 'Starts in {minutes} min',
    'reservations.count': '{count} total reservations',
    'reservations.tab.upcoming': 'Upcoming',
    'reservations.tab.active': 'Active',
    'reservations.tab.history': 'History',
    'reservations.status.scheduled': 'Scheduled',
    'reservations.status.active': 'In progress',
    'reservations.status.completed': 'Completed',
    'reservations.status.cancelled': 'Cancelled',
    'reservations.error.title': 'Could not load your reservations',
    'reservations.empty.upcoming.title': 'No upcoming reservations',
    'reservations.empty.upcoming.desc': 'When you book a walk, it will appear here automatically.',
    'reservations.empty.active.title': 'No active walks',
    'reservations.empty.active.desc': 'Active walks will appear here with live tracking access.',
    'reservations.empty.history.title': 'No history yet',
    'reservations.empty.history.desc': 'Your completed walks will show up in this section.',

    // Profile
    'profile.title': 'My Profile',
    'profile.subtitle.view': 'Your account and preferences',
    'profile.subtitle.edit': 'Update your information',
    'profile.loading': 'Loading profile...',
    'profile.edit': 'Edit profile',
    'profile.edit.photo': 'Tap the icon to change photo',
    'profile.notSet': 'Not set',
    'profile.save.success': 'Changes saved successfully',
    'profile.save.error': 'Could not save profile',
    'profile.logout': 'Log out',
    'profile.section.contact': 'Contact information',
    'profile.section.pets': 'My pets',
    'profile.section.pets.desc': 'Summary of your registered companions',
    'profile.section.account': 'Account',
    'profile.section.preferences': 'Privacy & preferences',
    'profile.section.accessibility': 'Accessibility',
    'profile.field.name': 'Full name',
    'profile.field.email': 'Email',
    'profile.field.phone': 'Phone',
    'profile.field.neighborhood': 'Neighborhood',
    'profile.field.emergency': 'Emergency contact',
    'profile.field.emergencyPhone': 'Emergency phone',
    'profile.pets.viewAll': 'View all',
    'profile.pets.empty': 'No pets registered yet',
    'profile.pets.more': '+{count} more',
    'profile.account.security': 'Security',
    'profile.account.security.desc': 'Password protected with Supabase Auth',
    'profile.account.member': 'Membership',
    'profile.account.member.desc': 'Pawalk free plan',
    'profile.prefs.notifications': 'Active notifications',
    'profile.prefs.push': 'Push',
    'profile.prefs.email': 'Email',
    'profile.prefs.sms': 'SMS',
    'profile.prefs.none': 'None active',
    'profile.prefs.push.desc': 'Real-time alerts',
    'profile.prefs.email.desc': 'Confirmations and summaries',
    'profile.prefs.sms.desc': 'Urgent updates only',
    'profile.a11y.largeText': 'Large text',
    'profile.a11y.largeText.desc': 'Increase text size across the app',
    'profile.a11y.reduceMotion': 'Reduce motion',
    'profile.a11y.reduceMotion.desc': 'Minimize movement in transitions',

    // Home
    'home.title': 'Where do you need a walker?',
    'home.search': 'Search by location...',
    'home.nearby': 'Nearby walkers',
    'home.filters': 'Filters',
    'home.distance': 'Distance',
    'home.price': 'Price',
    'home.rating': 'Rating',
    'home.service': 'Service',

    // Walker Profile
    'walker.verified': 'Verified',
    'walker.experience': 'Experience',
    'walker.years': 'years',
    'walker.reviewsTitle': 'Reviews',
    'walker.reviews.viewAll': 'See all reviews',
    'walker.reviews': 'reviews',
    'walker.book': 'Book Walk',
    'walker.about': 'About',
    'walker.certifications': 'Certifications',
    'walker.cert.id': 'Identity Verification',
    'walker.cert.background': 'Background Check',
    'walker.cert.firstaid': 'Veterinary First Aid',

    // Pet Profile
    'pet.add': 'Add Pet',
    'pet.name': 'Name',
    'pet.breed': 'Breed',
    'pet.age': 'Age',
    'pet.weight': 'Weight',
    'pet.behavior': 'Behavior',
    'pet.vaccinations': 'Vaccinations',
    'pet.friendly': 'Friendly',
    'pet.energetic': 'Energetic',
    'pet.shy': 'Shy',
    'pet.trained': 'Trained',
    'pet.playful': 'Playful',
    'pet.calm': 'Calm',
    'pet.gender': 'Gender',
    'pet.male': 'Male',
    'pet.female': 'Female',
    'pet.species': 'Species',
    'pet.dog': 'Dog',
    'pet.cat': 'Cat',

    // Booking
    'booking.select.date': 'Select date',
    'booking.select.time': 'Select time',
    'booking.duration': 'Duration',
    'booking.30min': '30 minutes',
    'booking.60min': '60 minutes',
    'booking.90min': '90 minutes',
    'booking.terms': 'Terms and conditions',
    'booking.accept': 'I accept the terms and coexistence rules',
    'booking.accept.confirmed': 'Terms accepted',
    'booking.cancel.policy': 'Cancellation policy',
    'booking.rules': 'Coexistence rules',
    'booking.confirmed.title': 'Booking confirmed!',
    'booking.confirmed.subtitle': 'Your walk has been scheduled successfully',
    'booking.confirmed.walker': 'Verified professional walker',
    'booking.confirmed.date': 'Walk date',
    'booking.confirmed.time': 'Time and duration',
    'booking.confirmed.note': 'Reservation status',
    'booking.confirmed.upcoming': 'It will appear under Upcoming. Live tracking unlocks when the walk starts.',
    'booking.confirmed.viewReservations': 'View my reservations',
    'booking.confirmed.backHome': 'Back to home',
    'booking.confirmed.hint': 'You will receive reminders before your walk',

    // Checkout
    'checkout.summary': 'Summary',
    'checkout.service': 'Walk service',
    'checkout.platform.fee': 'Platform fee (15%)',
    'checkout.total': 'Total',
    'checkout.payment': 'Payment method',
    'checkout.confirm': 'Confirm Payment',

    // Live Tracking
    'tracking.walker.on.way': 'Walker on the way',
    'tracking.walk.started': 'Walk started',
    'tracking.eta': 'Estimated time',
    'tracking.emergency': 'Emergency',
    'tracking.contact.walker': 'Contact walker',
    'tracking.completed': 'Walk completed! 🎉',

    // Notifications
    'notif.booking.confirmed': 'Booking confirmed',
    'notif.walk.started': 'Walk started',
    'notif.walk.completed': 'Walk completed',
    'notif.payment.confirmed': 'Payment confirmed',
    'notif.vaccination.reminder': 'Vaccination reminder',

    // Reminders
    'reminders.title': 'Reminders',
    'reminders.subtitle': "Don't forget your pet's care needs",
    'reminders.badge': 'Scheduled care',
    'reminders.add': 'New reminder',
    'reminders.edit': 'Edit reminder',
    'reminders.create': 'Create reminder',
    'reminders.manage': 'Manage reminders',
    'reminders.sectionDesc': 'Vaccines, medication, walks and more',
    'reminders.sectionEmpty': 'Schedule reminders for daily pet care',
    'reminders.sectionPending': '{count} pending',
    'reminders.sectionOverdue': '{count} overdue',
    'reminders.markComplete': 'Mark as completed',
    'reminders.snooze': 'Remind me in 10 min',
    'reminders.dismiss': 'Dismiss',
    'reminders.overdueHint': 'This reminder is overdue',
    'reminders.noPetSelected': 'No pet assigned',
    'reminders.tab.upcoming': 'Upcoming',
    'reminders.tab.overdue': 'Overdue',
    'reminders.tab.completed': 'Completed',
    'reminders.tab.all': 'All',
    'reminders.status.upcoming': 'Upcoming',
    'reminders.status.overdue': 'Overdue',
    'reminders.status.completed': 'Completed',
    'reminders.empty.title': 'No reminders yet',
    'reminders.empty.desc': 'Create your first reminder for vaccines, medication, walks and more.',
    'reminders.delete.title': 'Delete reminder',
    'reminders.delete.desc': 'Delete "{title}"? This action cannot be undone.',
    'reminders.alert.title': 'Reminder',
    'reminders.form.subtitle': 'Schedule alerts for your pet care',
    'reminders.form.title': 'Title',
    'reminders.form.titlePlaceholder': 'E.g. Annual vaccine, flea pill',
    'reminders.form.pet': 'Pet',
    'reminders.form.noPet': 'No specific pet',
    'reminders.form.category': 'Category',
    'reminders.form.date': 'Date',
    'reminders.form.time': 'Time',
    'reminders.form.notes': 'Notes (optional)',
    'reminders.form.notesPlaceholder': 'Details, dosage, vet clinic...',
    'reminders.form.alertHint': 'We will notify you at the scheduled date and time',
    'reminders.category.vaccination': 'Vaccines',
    'reminders.category.medication': 'Medication',
    'reminders.category.deworming': 'Deworming',
    'reminders.category.walks': 'Walks',
    'reminders.category.feeding': 'Feeding',
    'reminders.category.grooming': 'Grooming',
    'reminders.category.vet_visit': 'Vet appointment',

    // Common
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'back': 'Back',
    'next': 'Next',
    'skip': 'Skip',
    'done': 'Done',
    'from': 'from',
    'min': 'min',
    'hour': 'hour',
    'available': 'Available',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
